source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'Gradients'

pod 'Hue', path: '../../'
pod 'Imaginary', git: 'https://github.com/systembugtj/Imaginary.git'
pod 'Cache', git: 'https://github.com/systembugtj/Cache.git'
pod 'Spots', git: 'https://github.com/systembugtj/Spots'
pod 'Sugar', git: 'https://github.com/systembugtj/Sugar'
pod 'Tailor', git: 'https://github.com/systembugtj/Tailor'
pod 'Fakery', git: 'https://github.com/systembugtj/Fakery'
